spring.application.name=backend-papiro
server.port=3333

# Conexao PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/rodney-papiro?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate / JPA (Cria/atualiza tabelas automaticamente)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect